variables:
  GIT_STRATEGY: clone

build:
  stage: build
  tags: ["dalfcs_gitlab_docker_ci"]
  image: gradle:alpine
  script: ./gradlew assemble

test:
  stage: test
  tags: ["dalfcs_gitlab_docker_ci"]
  image: gradle:alpine
  script: ./gradlew check




